# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photowall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Whatsup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('time', models.DateField()),
            ],
        ),
    ]
