# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170622_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsup',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsup',
            name='time',
            field=models.DateField(),
        ),
    ]
