# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('category', models.CharField(choices=[('DL', 'Deep Learning'), ('PGM', 'Probabilistic Graphical Model'), ('CO', 'Convex Optimization'), ('RD', 'Random Exploration')], default='DL', max_length=3)),
                ('abstract', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('category', models.CharField(choices=[('DL', 'Deep Learning'), ('PGM', 'Probabilistic Graphical Model'), ('CO', 'Convex Optimization'), ('RD', 'Random Exploration')], default='DL', max_length=3)),
                ('type', models.CharField(choices=[('TT', 'Tutorial'), ('DM', 'DEMO'), ('NS', 'NEWS')], default='DL', max_length=3)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
