# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Need Valid Phone Number', regex='^(\\([0-9]{3}\\)|[0-9]{3}-)[0-9]{3}-[0-9]{4}$')])),
                ('address', models.CharField(max_length=200)),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to=b'')),
            ],
        ),
    ]
