# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20170625_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='coauthers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='code_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.CharField(choices=[('AAAI', 'Association for the Advancement of Artificial Intelligence (AAAI)'), ('NIPS', 'Neural Information Processing Systems (NIPS)'), ('IJCAI', 'International Joint Conference on Artificial Intelligence (IJCAI)'), ('ICML', 'International Conference on Machine Learning (ICML)'), ('ARXIV', 'ArXiv- Waiting for Publication')], default='AAAI', max_length=10),
        ),
    ]
